spring.datasource.url=jdbc:postgresql://localhost:5432/autokolcsonzo
spring.datasource.username=postgres
spring.datasource.password=postgre1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
